const int EMPTY_SCHEDULE = 0;
const int FILL_CIRCLE = EMPTY_SCHEDULE + 1;
const int LEFT_HALF_SCHEDULE = FILL_CIRCLE + 1;
const int FULL_SCHEDULE = LEFT_HALF_SCHEDULE + 1;
const int RIGHT_HALF_SCHEDULE = FULL_SCHEDULE + 1;
const int RED_DAY = RIGHT_HALF_SCHEDULE + 1;
const int GREY_DAY = RED_DAY + 1;